# Pull in the main make targets

DIM=3
TINY_PROFILE=TRUE
NETWORK_DIR=aprox13
USE_MPI=TRUE
USE_CUDA=TRUE
USE_OMP=FALSE
USE_SIMPLIFIED_SDC=TRUE

include $(CASTRO_HOME)/Exec/science/wdmerger/GNUmakefile
