# Problem-specific makefile variables

EOS_dir=gamma_law_general

# Problem-specific variables

stop_time = 15.0

geometry.prob_lo = 0.00e9 0.00e9 0.00e9
geometry.prob_hi = 5.12e9 5.12e9 5.12e9

castro.do_rotation = 0

# Main make target

all: make_castro

# Pull in main makefile

include $(WDMERGER_HOME)/job_scripts/makefile
