# Problem-specific variables

mass_P = 0.90
mass_S = 0.60

castro.do_hydro = 0
castro.do_rotation = 0

max_step = 0

# Main make target

all: make_castro

# Pull in main makefile

include $(WDMERGER_HOME)/job_scripts/makefile
