# Pull in CASTRO makefile for the uniform cube/sphere,
# but use the wdmerger diagnostics routines.

Blocs := $(WDMERGER_HOME)/source/diagnostics/
Bpack := $(WDMERGER_HOME)/source/diagnostics/Make.package

include $(CASTRO_DIR)/Exec/uniform_cube_sphere/GNUmakefile
