# Set the parameters that are unique for this test
EOS_dir=gamma_law_general
DIM=2
USE_GRAV=FALSE

# Main make target

all: make_castro

# Pull in main makefile

include $(WDMERGER_HOME)/job_scripts/makefile
