# Pull in CASTRO makefile for the KH problem,
# but use the wdmerger diagnostics routines.

Blocs := $(WDMERGER_HOME)/source/diagnostics/
Bpack := $(WDMERGER_HOME)/source/diagnostics/Make.package

include $(CASTRO_DIR)/Exec/KH/GNUmakefile
