# Problem-specific makefile variables

EOS_dir=gamma_law_general
DIM=2
USE_GRAV=FALSE
USE_ROTATION=FALSE

# Problem-specific variables

geometry.is_periodic = 1 1

geometry.prob_lo = 0.0 0.0
geometry.prob_hi = 1.0 1.0

castro.lo_bc       =  0 0
castro.hi_bc       =  0 0

# Pull in main makefile

include $(WDMERGER_HOME)/source/GNUmakefile
