# Problem-specific variables

mass_P:=0.90
mass_S:=0.60

castro.rotational_period:=100.0

max_step:=10

amr.n_cell = 256 256 256

amr.checkpoint_files_output = 0

# Main make target

all: make_castro

# Pull in main makefile

include $(WDMERGER_HOME)/job_scripts/makefile
