# Problem-specific makefile variables

EOS_dir=gamma_law_general

# Problem-specific variables

stop_time = 15.0

geometry.prob_lo = -2.56e9 -2.56e9 -2.56e9
geometry.prob_hi =  2.56e9  2.56e9  2.56e9

castro.do_rotation = 0

# Pull in main makefile

include $(WDMERGER_HOME)/source/GNUmakefile
