# Pull in CASTRO makefile for the Evrard collapse,
# but use the wdmerger diagnostics routines.

Blocs := $(WDMERGER_HOME)/source/diagnostics/
Bpack := $(WDMERGER_HOME)/source/diagnostics/Make.package

include $(CASTRO_DIR)/Exec/evrard_collapse/GNUmakefile
