# Problem-specific variables

geometry.prob_lo =  -1.6 -1.6 -1.6
geometry.prob_hi =   1.6  1.6  1.6

castro.do_hydro = 0
castro.do_rotation = 0

castro.small_dens = 1.e-10

max_step = 0

gravity.direct_sum_bcs = 1

# Main make target

all: make_castro

# Pull in main makefile

include $(WDMERGER_HOME)/job_scripts/makefile
