# Problem-specific variables

USE_ROTATION = FALSE

mass_P =  0.90
mass_S = -1.00

geometry.prob_lo   =  0.       0.       0.
geometry.prob_hi   =  2.56e9   2.56e9   2.56e9

# Main make target

all: make_castro

# Pull in main makefile

include $(WDMERGER_HOME)/job_scripts/makefile
